id: kafka-manager-unauth

info:
  name: kafka manager unauth
  author: pikpikcu
  severity: info
  description: Manage/Monitor sensitive information in Kafka

  # Google-Dork:inurl:/clusters intitle:"kafka Manager"

requests:
  - method: GET
    path:
      - "{{BaseURL}}/"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "Kafa Manager"
          - "<title>Kafka Manager</title>"
          - "Add Cluster"
        part: body
      - type: status
        status:
          - 200
